Fixed `explicit specialization` compiler error of NativeInvokationManager::allocate
When compiling against clang, the compiler would complain of following error:

```
error: explicit specialization of
      'allocate' in class scope
       static void * allocate<jvalue *>(jvalue * const values) {
```

However, since we can't specialize template functions of template
classes outside of them without first specializing said template class
first, a workaround solution is to add a stub template struct and
forward allocate method to it.